name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "ci"
  cancel-in-progress: false

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'
        env:
          ACTIONS_STEP_DEBUG: false
          ACTIONS_RUNNER_DEBUG: false
      - name: Run tests
        run: bash test/run.sh
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Run coverage tests
        run: npx jest --coverage
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
