name: NPM

on:
  push:
    paths:
      - 'package.json'
      - '.github/workflows/publish.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: "npm"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Build
        run: bash src/build.sh

      - name: Publish to npm
        run: npm publish --access public || npm publish --access public --tag beta

      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@${{ github.repository_owner }}'
      - name: Publish to GitHub Packages
        run: npm publish || npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

